import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


function Navbar() {
  return (
    <nav style={{
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      padding: "1rem 2rem",
      background: "#fff",
      borderBottom: "1px solid #eee",
      fontFamily: "var(--font-geist-sans)",
    }}>
      <div style={{ fontWeight: 700, fontSize: "1.2rem" }}>My Portfolio</div>
      <div style={{ display: "flex", gap: "1.5rem" }}>
        <a href="/" style={{ textDecoration: "none", color: "#333" }}>Home</a>
        <a href="/about" style={{ textDecoration: "none", color: "#333" }}>About</a>
        <a href="/projects" style={{ textDecoration: "none", color: "#333" }}>Projects</a>
        <a href="/contact" style={{ textDecoration: "none", color: "#333" }}>Contact</a>
      </div>
    </nav>
  );
}

function Footer() {
  return (
    <footer style={{
      textAlign: "center",
      padding: "1rem 0",
      background: "#fafafa",
      borderTop: "1px solid #eee",
      fontSize: "0.95rem",
      color: "#888",
      fontFamily: "var(--font-geist-sans)",
      marginTop: "2rem"
    }}>
      © {new Date().getFullYear()} My Portfolio. All rights reserved.
    </footer>
  );
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} style={{ margin: 0, minHeight: "100vh", display: "flex", flexDirection: "column" }}>
        <Navbar />
        <main style={{ flex: 1, width: "100%", maxWidth: 1200, margin: "0 auto", padding: "2rem 1rem" }}>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
